export const UPDATE_MEMBER_DATA = 'UPDATE_MEMBER_DATA';
export const SOCKET_UPDATE_MEMBER_DATA = 'SOCKET_UPDATE_MEMBER_DATA';
export const SOCKET_BROADCAST_UPDATE_MEMBER_DATA = 'SOCKET_BROADCAST_UPDATE_MEMBER_DATA';
