export const FETCH_USER = 'FETCH_USER';
export const FETCH_USERS = 'FETCH_USERS';
export const SOCKET_BROADCAST_MUTE_USER = 'SOCKET_BROADCAST_MUTE_USER';
export const SOCKET_BROADCAST_UNMUTE_USER = 'SOCKET_BROADCAST_UNMUTE_USER';
