export const FETCH_BANNED_USERS = 'FETCH_BANNED_USERS';
export const BAN_USER = 'BAN_USER';
export const SOCKET_BAN_USER = 'SOCKET_BAN_USER';
export const SOCKET_BROADCAST_BAN_USER = 'SOCKET_BROADCAST_BAN_USER';
export const UNBAN_USER = 'UNBAN_USER';
export const UNBAN_ALL_USERS = 'UNBAN_ALL_USERS';
