export const START_LIVE_VIDEO = 'START_LIVE_VIDEO';
export const SOCKET_START_LIVE_VIDEO = 'SOCKET_START_LIVE_VIDEO';
export const SOCKET_BROADCAST_START_LIVE_VIDEO = 'SOCKET_BROADCAST_START_LIVE_VIDEO';
export const END_LIVE_VIDEO = 'END_LIVE_VIDEO';
export const SOCKET_END_LIVE_VIDEO = 'SOCKET_END_LIVE_VIDEO';
export const SOCKET_BROADCAST_END_LIVE_VIDEO = 'SOCKET_BROADCAST_END_LIVE_VIDEO';
