export const SOCKET_REQUEST_VIDEO_CALL = 'SOCKET_REQUEST_VIDEO_CALL';
export const SOCKET_BROADCAST_REQUEST_VIDEO_CALL = 'SOCKET_BROADCAST_REQUEST_VIDEO_CALL';
export const SOCKET_REJECT_VIDEO_CALL = 'SOCKET_REJECT_VIDEO_CALL';
export const SOCKET_BROADCAST_REJECT_VIDEO_CALL = 'SOCKET_BROADCAST_REJECT_VIDEO_CALL';
export const SOCKET_ACCEPT_VIDEO_CALL = 'SOCKET_ACCEPT_VIDEO_CALL';
export const SOCKET_BROADCAST_ACCEPT_VIDEO_CALL = 'SOCKET_BROADCAST_ACCEPT_VIDEO_CALL';
