export const FETCH_USER = 'FETCH_USER';
export const FETCH_USERS = 'FETCH_USERS';
export const SOCKET_BROADCAST_KICK_USER = 'SOCKET_BROADCAST_KICK_USER';
export const SOCKET_BROADCAST_UNKICK_USER = 'SOCKET_BROADCAST_UNKICK_USER';
